name: Build & Push to AWS ECR

on:
  push:
    branches: [ main ]

jobs:
  build-and-push-ecr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 224888985313.dkr.ecr.eu-north-1.amazonaws.com

    - name: Build, tag, and push Docker image to ECR
      run: |
        docker build -t multi-cloud-cicd-app .
        docker tag multi-cloud-cicd-app:latest 224888985313.dkr.ecr.eu-north-1.amazonaws.com/multi-cloud-cicd-app:latest
        docker push 224888985313.dkr.ecr.eu-north-1.amazonaws.com/multi-cloud-cicd-app:latest
